export const tasks = [
	// Setup
	{ stage: '01',customClass: '-done', badgeClass: '-done', badgeLabel: "Completed", title: "Crafting the Landing Page", description: "Our first impression matters. We’ve built a landing page that captures our values and invites users to explore Mistaek’s offerings." },
	{ stage: '01',customClass: '-done', badgeClass: '-done', badgeLabel: "Completed", title: "Building the About Page", description: "An inside look at Mistaek’s mission, values, and the purpose driving our design philosophy. Meet the brand behind the vision." },
	{ stage: '01',customClass: '-done', extraBadgeLabel: 'v1.0', badgeClass: '-done', badgeLabel: "Completed", title: "Website Launch", description: "The foundation of Mistaek’s online presence. Version 1 sets the stage for a seamless, inviting user experience that reflects our expertise." },
	{ stage: '01',customClass: '-done', badgeClass: '-done', badgeLabel: "Completed", title: "Setting Up Blog & Newsletter", description: "Connecting with our audience through meaningful content. Our Ghost blog and newsletter are designed to provide regular, insightful updates." },
	{ stage: '01',customClass: '-done', badgeClass: '-done', badgeLabel: "Completed", title: "Establishing the Roadmap Page", description: "Transparency at its finest. A public roadmap where clients and followers can track our progress and upcoming initiatives." },
	{ stage: '01',customClass: '', extraBadgeLabel: 'Client Deck', badgeClass: '-validation', badgeLabel: "Validation", title: "Crafting the Client Agreement", description: "A structured, accessible client agreement deck that ensures every collaboration starts with clear terms and mutual understanding." },
	{ stage: '01',customClass: '', extraBadgeLabel: 'Client Deck', badgeClass: '-validation', badgeLabel: "Validation", title: "Presenting the Client Proposal", description: "Our proposal deck is designed to clearly outline project scope, deliverables, and how Mistaek’s approach aligns with client goals." },
	{ stage: '01',customClass: '', extraBadgeLabel: 'Stage 03', badgeClass: '-subtle', badgeLabel: "Migrated", title: "Launching the Mistaek YouTube Channel", description: "Introducing Mistaek on YouTube! We’re creating a YouTube channel to share our journey, showcase our design process, and connect with our community through inspiring and informative content." },
	// Services
	{ stage: '02',customClass: '-done', badgeClass: '-done', badgeLabel: "Completed", title: "Structuring Consultation Tiers", description: "Offering flexible consultation options tailored to meet our clients at every stage of their journey. Each tier is crafted to bring clarity and impact." },
	{ stage: '02',customClass: '-done', extraBadgeLabel: 'Client Deck', badgeClass: '-done', badgeLabel: "Completed", title: "Client Design Snapshot", description: "A sneak peek into our clients needs, crafted into a deck that showcases how we can help and elevate design for our them." },
	{ stage: '02',customClass: '', extraBadgeLabel: 'Client Deck', badgeClass: '-validation', badgeLabel: "Validation", title: "Client Onboarding Guide", description: "Consistency starts here. This is the foundation of everything we create for you." },
	{ stage: '02',customClass: '', extraBadgeLabel: 'Client Deck', badgeClass: '-progress', badgeLabel: "In Progress", title: "Client Action Blueprint", description: "A detailed roadmap for clients, providing actionable next steps and strategies for achieving their design goals." },
	{ stage: '02',customClass: '', badgeClass: '-planned', badgeLabel: "Planned", title: "Starting Our Design System", description: "A versatile system that powers our work and yours. Perfect for faster projects, better designs, and even client subscriptions." },
	{ stage: '02',customClass: '', badgeClass: '-planned', badgeLabel: "Planned", title: "Quote Tool for Service Tiers", description: "Transparent pricing at your fingertips. We’ve made it simple to explore service options that work for you." },
	// Growth & Community
	{ stage: '03',customClass: '', badgeClass: '-planned', badgeLabel: "Planned", title: "Optimising Analytics, SEO & Accessibility", description: "A full assessment to ensure our website is optimised for visibility, accessibility, and meaningful engagement." },
	{ stage: '03',customClass: '', badgeClass: '-planned', badgeLabel: "Planned", title: "Launching Automated Email Series", description: "Staying connected through automated email sequences, designed to keep clients and followers informed on Mistaek’s latest." },
	{ stage: '03',customClass: '', badgeClass: '-planned', badgeLabel: "Planned", title: "Showcasing the Case Studies Page", description: "A dedicated space to feature our past work, illustrating Mistaek’s approach and the success of our client partnerships." },
	{ stage: '03',customClass: '', badgeClass: '-planned', badgeLabel: "Planned", title: "Building a Feedback Hub", description: "Listening is key. This feature lets our community share insights and ideas to shape Mistaek’s future." },
	{ stage: '03',customClass: '', extraBadgeLabel: 'Stage 02', badgeClass: '-planned', badgeLabel: "Planned", title: "Launching the Mistaek YouTube Channel", description: "Introducing Mistaek on YouTube! Our first video shares our mission, services, and approach to impactful design." },
	// Scaling
	{ stage: '04',customClass: '', extraBadgeLabel: 'Client Deck', badgeClass: '-planned', badgeLabel: "Planned", title: "Completing the Client Offboarding Guide", description: "Our offboarding deck ensures clients feel supported as projects conclude, with resources to maintain long-term success." },
	{ stage: '04',customClass: '', badgeClass: '-planned', badgeLabel: "Planned", title: "Implementing a Maintenance Model", description: "Offering ongoing support to clients, with a structured maintenance plan to keep projects evolving and relevant." },
	{ stage: '04',customClass: '', badgeClass: '-planned', badgeLabel: "Planned", title: "Creating a Web Accessibility Audit Tool", description: "A project to make the web better for everyone—designing tools that empower brands to audit and improve accessibility." },
	{ stage: '04',customClass: '', badgeClass: '-planned', badgeLabel: "Planned", title: "Quarterly Webinar Series", description: "Big ideas, shared live. These optional sessions dive into design, strategy, and growth." },
	{ stage: '04',customClass: '', badgeClass: '-planned', badgeLabel: "Planned", title: "Starting a Referral Program", description: "Good work is worth sharing. We’re creating a program to reward those who help us grow." },
];